{"name": "test_with_invalid_credentials", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = <bound method LoginPage.verify_user_has_not_logged_in of <pageObjects.LoginPage.LoginPage object at 0x00000169B3E6D1E0>>()\n +    where <bound method LoginPage.verify_user_has_not_logged_in of <pageObjects.LoginPage.LoginPage object at 0x00000169B3E6D1E0>> = <pageObjects.LoginPage.LoginPage object at 0x00000169B3E6D1E0>.verify_user_has_not_logged_in", "trace": "self = <Tests.test_Login.TestLogin object at 0x00000169B3E3AA10>\n\n    def test_with_invalid_credentials(self):\n        homepage = HomePage(self.driver)\n        loginpage = homepage.navigate_to_login_page()\n        loginpage.Login_to_UI(self.generate_email_with_timestamp(), \"12789\")\n>       assert loginpage.verify_user_has_not_logged_in()\nE       assert False\nE        +  where False = <bound method LoginPage.verify_user_has_not_logged_in of <pageObjects.LoginPage.LoginPage object at 0x00000169B3E6D1E0>>()\nE        +    where <bound method LoginPage.verify_user_has_not_logged_in of <pageObjects.LoginPage.LoginPage object at 0x00000169B3E6D1E0>> = <pageObjects.LoginPage.LoginPage object at 0x00000169B3E6D1E0>.verify_user_has_not_logged_in\n\ntest_Login.py:20: AssertionError"}, "start": 1718561496463, "stop": 1718561497644, "uuid": "fa0b784c-3ce5-4027-b98a-96afdecf8a71", "historyId": "e930fbf7432442d4b6934232374e6f70", "testCaseId": "e930fbf7432442d4b6934232374e6f70", "fullName": "test_Login.TestLogin#test_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-ESL8NRHA"}, {"name": "thread", "value": "7244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Login"}]}