{"name": "test_empty_credentials", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = <bound method LoginPage.verify_user_has_not_logged_in of <pageObjects.LoginPage.LoginPage object at 0x00000169B3E3B700>>()\n +    where <bound method LoginPage.verify_user_has_not_logged_in of <pageObjects.LoginPage.LoginPage object at 0x00000169B3E3B700>> = <pageObjects.LoginPage.LoginPage object at 0x00000169B3E3B700>.verify_user_has_not_logged_in", "trace": "self = <Tests.test_Login.TestLogin object at 0x00000169B3E3BE20>\n\n    def test_empty_credentials(self):\n        homepage = HomePage(self.driver)\n        loginpage = homepage.navigate_to_login_page()\n        loginpage.Login_to_UI(\"\", \"\")\n>       assert loginpage.verify_user_has_not_logged_in()\nE       assert False\nE        +  where False = <bound method LoginPage.verify_user_has_not_logged_in of <pageObjects.LoginPage.LoginPage object at 0x00000169B3E3B700>>()\nE        +    where <bound method LoginPage.verify_user_has_not_logged_in of <pageObjects.LoginPage.LoginPage object at 0x00000169B3E3B700>> = <pageObjects.LoginPage.LoginPage object at 0x00000169B3E3B700>.verify_user_has_not_logged_in\n\ntest_Login.py:27: AssertionError"}, "start": 1718561509625, "stop": 1718561512270, "uuid": "d97d44d4-2c10-4e5d-baed-11367988458f", "historyId": "9b95d0c631194bf5e66defedf618cc5d", "testCaseId": "9b95d0c631194bf5e66defedf618cc5d", "fullName": "test_Login.TestLogin#test_empty_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-ESL8NRHA"}, {"name": "thread", "value": "7244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Login"}]}