{"name": "test_empty_credentials", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = <bound method LoginPage.verify_user_has_not_logged_in of <pageObjects.LoginPage.LoginPage object at 0x00000156B6D3DAB0>>()\n +    where <bound method LoginPage.verify_user_has_not_logged_in of <pageObjects.LoginPage.LoginPage object at 0x00000156B6D3DAB0>> = <pageObjects.LoginPage.LoginPage object at 0x00000156B6D3DAB0>.verify_user_has_not_logged_in", "trace": "self = <Tests.test_Login.TestLogin object at 0x00000156B6D3D3F0>\n\n    def test_empty_credentials(self):\n        homepage = HomePage(self.driver)\n        loginpage = homepage.navigate_to_login_page()\n        loginpage.Login_to_UI(\"\", \"\")\n>       assert loginpage.verify_user_has_not_logged_in()\nE       assert False\nE        +  where False = <bound method LoginPage.verify_user_has_not_logged_in of <pageObjects.LoginPage.LoginPage object at 0x00000156B6D3DAB0>>()\nE        +    where <bound method LoginPage.verify_user_has_not_logged_in of <pageObjects.LoginPage.LoginPage object at 0x00000156B6D3DAB0>> = <pageObjects.LoginPage.LoginPage object at 0x00000156B6D3DAB0>.verify_user_has_not_logged_in\n\ntest_Login.py:27: AssertionError"}, "start": 1718613267647, "stop": 1718613268823, "uuid": "92783de2-dbf3-4939-979b-39ec063c4e42", "historyId": "9b95d0c631194bf5e66defedf618cc5d", "testCaseId": "9b95d0c631194bf5e66defedf618cc5d", "fullName": "test_Login.TestLogin#test_empty_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-ESL8NRHA"}, {"name": "thread", "value": "3052-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Login"}]}